# 1.1 프로그램 오류

## 에러란?
- 프로그램이 실행 중 오작동 하거나 비정상적으로 종료되는 경우, <br />
이러한 결과를 초래하는 `원인`을 프로그램 에러 또는 오류라고 한다 

## 발생시점에 따른 에러 종류
### 컴파일 에러 (compile-time error)
- 컴파일 할 때 발생하는 에러

### 런타임에러(runtime error)
- 프로그램의 실행도중 발생하는 에러 

## 논리적 에러
- 컴파일도 잘되고 실행도 잘되지만 의도한 것과 다르게 동작하는 경우 <br />
    - ex) 재고가 음수가 됨, 게임에서 비행기가 총알을 맞아도 죽지 않음
    

## 자바에서 오류를 클래스로 정의한 이유

- 소스코드를 `컴파일` 하면 컴파일러가 `소스코드(*.java)`에 대해  <br /.
오타나 잘못된 구문, 자료형 체크 등 `기본적인 검사`를 수행하여 오류가 있는지 알려 준다. <br />
컴파일러가 알려 준 에러들을 모두 수정해서 컴파일을 성공하면, `클래스 파일(*.class)`이 생성되고, <br />
이를 실행할 수 있다.<>

- 컴파일을 에러없이 성공적으로 마쳐도, 실행도중 발생할 수 있는 `잠재적인 오류`까지 검사할 수 없기 때문에 <br />
실행 중에 `에러`에 의해 `잘못된 결과`를 얻거나 `프로그램이 비정상적으로 종료`될 수 있다. <br />

-  이러한 런타임 에어를 방지하기 위해서는 프로그램의 실행도중 발생할 수 있는 모든 경우의 수를 고려하여 이에 대해 대비 하는 것이 필요했고,
자바에서는 실행 시 (runtime) 발생할 수 있는 프로그램 오류를 1. 에러, 2. 오류 두 가지로 구분했다. 

### 에러(error)
- 프로그램 코드에 의해서 복구 할 수 없는 심각한 오류, 프로그램의 비정상적인 종료를 막을 수 없다. 
    - 메로리 부족(OutOfMemoryError), StackOverFlowError

### 예외(exception)
- 프로그램 코드에 의해서 수습될 수 있는 다소 미약한 오류, <br />
프로그래머가 적절한 코드를 미리 작성해 프로그램의 비정상적인 종료를 막을 수 있다.

# 1.2 예외 클래스의 계층구조
- 자바에서는 실행 시 발생할 수 있는 오류(Exception과 Error)를 클래스로 정의하였다. <br />
Exception, Error 클래스 역시 Object클래스의 자손들이다. 

![오류클래스계층구조](https://user-images.githubusercontent.com/40673012/91649107-29cf9a80-eaab-11ea-873c-9fbb166e3c0b.jpg)

- 모든 예외의 최고 조상은 Exception클래스이다.

![예외클래스계층구조](https://user-images.githubusercontent.com/40673012/91649112-3e139780-eaab-11ea-823f-c2c8d56aec6a.jpg)

- 위 그림에서 볼 수 있듯이 예외 클래스들은 다음과 같이 두 그룹으로 나뉜다 <br />
1. Exception클래스와 그 자손들
2. RuntimeException클래스와 그 자손들

## RuntimeException클래스
- 주로 `프로그래머의 실수`에 의해서 발생될 수 있는 예외들로, 자바의 프로그래밍 요소들과 관계 깊다
    - ex) 배열의 범위를 벗어남(ArrayIndexOutOfBoundsException),
    값이 null인 참조변수의 멤버를 호출함(NullPointerException),
    클래스간의 형변환을 잘못함(ArithmeticException)

## Exception클래스
- 주로 `외부의 영향`으로 발생하며, 프로그램의 `사용자들의 동작`에 의해서 발생하는 경우가 많다
    - ex) 존재하지 않는 파일의 이름 입력(FileNotFoundException),
    실수로 클래스의 이름을 잘못 적음(ClassNotFoundException),
    입력한 데이터 형식이 잘못됨(DataFormatException)

# 1.3 예외처리하기 - try-catch문 

- 프로그램의 실행도중에 발생하는 에러는 어쩔 수 없지만, `예외`는 프로그래머가 이에 대한 처리를 미리 해주어야 한다.

## 예외 처리(exception handling)란?
- 정의:프로그램 실행 시 발생할 수 있는 예기치 못한 예외의 발생에 대비한 코드를 작성하는 것
- 목적: 프로그램의 `비정상 종료를 막고` 정상적인 실행상태를 유지하는 것<br />

- 발생한 예외를 처리하지 못하면, 프로그램은 비정상적으로 종료되며, <br />
처리되지 못한 예외(uncatcht exception)는 JVM의 `예외처리기(UncaughtExceptionHandler)`가 받아서<br />
예외의 원인을 화면에 출력한다.

## 예외를 처리하는 방법
- try-catch문을 사용한다

```java
int number =100;
int result = 0;

for(int i=0; i < 10; i++){
    //예외가 발생한 가능성이 있는 문장을 넣는다.
    try {
        result = number / (int) (Math.random() * 10);
        System.out.print(result);
    } catch (ArithmeticException e){
        //ArithmeticException 발생했을 경우, 이를 처리하기 위한 문장을 적는다.
        System.out.println("0");
    } catch (Exception e){
        //Exception이 발생했을 경우, 이를 처리하기 위한 문장을 적는다.
    }
}
```
- 위 코드처럼 `여러 종류의 예외`를 처리할 수 있도록 `하나 이상의 catch블럭`이 올 수 있으며, <br />
이 중 `발생한 예외의 종류`와 일치하는 단 한 개의 catch블럭만 수행된다. <br />
일치하는 catch블록이 없으면 예외는 처리되지 않는다. 

- if문과 달리 try블럭이나 catch블럭 내에 포함된 문장이 하나뿐이어도 괄호{}를 생략 불가

- catch블럭 내의 코드에서도 예외가 발생할 수 있으므로 <br />
try블럭 또는 catch블럭에 또 다른 try-catch문 포함 가능

```java
try{
    try {
        
    }catch (Exception e){
        
    }
}catch (Exception e){
    
}
```


# 1.5 예외의 발생과 catch블럭
- catch블럭은 괄호()와 블럭{} 두 부분으로 나눠져 있는데, 
`괄호()`내에는 `처리할 예외와 같은 타입의 참조변수`를 선언해야한다.

- 예외가 발생하면, `발생한 예외에 해당하는 클래스의 인스턴스`가 만들어 진다. <br />
예외가 발생한 문장이 try블럭에 포함되어 있다면, 이 예외를 처리할 수 있는 catch 블럭이 있는지 찾게 된다.

- 첫 번째 catch블럭부터 차례로 내려가면서 catch블록의 괄호()내에 `선언된 참조변수의 종류`와 
`생성된 예외클래스의 인스턴스`에  `instanceof연산자`를 이용해서 검사하고,
검사결과가 true인 catch블럭을 만날 때까지 검사는 계속된다.<br />

- 모든 예외 클래스는 Exception클래스의 자손이므로, 
catch블럭의 괄호()에 Exception클래스 타입의 참조변수를 선언하면,<br />
어떤 종류의 예외가 발생해도 이 catch블럭으로 처리된다.

- 아래 코드는 try블럭에서 ArithmeticException을 발생하여 catch블럭을 하나씩 차례로 검사한다. <br />
첫 번째 검사에서 일치하는 catch블럭을 찾기 때문에 두 번 째 catch블럭은 검사하지 않는다. 

- 만일 try블럭 내에서 ArithmeticException이 아닌 다른 종류의 예외가 발생한다면, <br /
Exception 클래스 타입의 참조 변수를 선언한 곳에서 처리되었을 것이다. <br />
이처럼 try-catch문의 마지막에 Exception클래스 타입의 참조변수를 선언한 catch블럭을 사용하면<br />
어떤 종류의 예외가 발생해도 catch블럭으로 처리할 수 있다.

```java
public class ExceptionEx7 {
    public static void main(String args[]){
        System.out.println(1);
        System.out.println(2);
        try{
            System.out.println(3);
            System.out.println(0/0); //0으로 나눠서 ArithmeticException발생
            System.out.println(4);   //실행되지 않는다.
        }catch (ArithmeticException ae){
            if(ae instanceof ArithmeticException)
                System.out.println("true");
            System.out.println("ArithmeticException");
        }catch (Exception e){ //ArithmeticException을 제외한 모든 예외 처리
            System.out.println("Exception");
        }//try-catch의 끝
        System.out.println(6);
    }
}
```
```
결과
1
2
3
true
ArithmeticException
6
```




# 1.6 예외 발생시키기

# 1.7 메서드에 예외 선언하기


